# Generated by Django 6.0 on 2026-01-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('customer', 'Customer')], default='admin', max_length=10),
        ),
    ]
