# Generated by Django 6.0 on 2026-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WAITER', 'Ofitsiant'), ('CUSTOMER', 'Foydalanuvchi')], default='CUSTOMER', max_length=20),
        ),
    ]
