# Generated by Django 6.0 on 2026-01-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Restarangacha bolgan masofa (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default='pending', max_length=20)),
            ],
        ),
    ]
