# Generated by Django 6.0 on 2026-01-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
        ('order', '0003_remove_order_items_alter_order_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='dish.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(help_text='Restarangacha bolgan masofa (km)'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
