# Generated by Django 6.0 on 2026-01-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_items_order_price_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(default=0.0, help_text='Masofa (km)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Savatda'), ('pending', 'Kutilmoqda (Tasdiqlangan)'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi')], default='cart', max_length=20),
        ),
    ]
